[[redirects]]
  from = "/api/esmfold"
  to   = "https://health.api.nvidia.com/v1/biology/nvidia/esmfold"
  status = 200
  force  = true

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "src/app/api"

[functions]
  included_node_modules = ["razorpay"]

[dev]
  command    = "bun dev"
  port       = 8888
  targetPort = 8080
  functions  = "src/app/api"