[[redirects]]
  from = "/api/esmfold"
  to   = "https://health.api.nvidia.com/v1/biology/nvidia/esmfold"
  status = 200
  force  = true

[[redirects]]
  from = "/api/alphafold2"
  to   = "https://health.api.nvidia.com/v1/biology/deepmind/alphafold2"
  status = 200
  force  = true

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

[build]
  command   = "npm run build"

[functions]
  external_node_modules = ["razorpay"]

[dev]
  command    = "bun dev"
  port       = 8888
  targetPort = 8080