// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jckbjiprworpsubqgugn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impja2JqaXByd29ycHN1YnFndWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTA0MjAsImV4cCI6MjA2MTA4NjQyMH0.odAEqBghObQzczMLrHKlptmqCfTlyvYCS_uFzxkMAi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);